export type ResponseRule = {
  pattern: RegExp;
  responses: string[];
  maxLength?: number;
  usesName?: boolean;
};

export const topicRules: Array<{ topic: string; patterns: RegExp[] }> = [
  {
    topic: 'planning',
    patterns: [/\broadmap\b/i, /\bmilestone\b/i, /\bdeadline\b/i, /\bscope\b/i, /\bplan\b/i],
  },
  {
    topic: 'release',
    patterns: [/\bdeploy\b/i, /\brelease\b/i, /\bpipeline\b/i, /\bbuild\b/i, /\bprod\b/i],
  },
  {
    topic: 'design',
    patterns: [/\bdesign\b/i, /\bmockup\b/i, /\bui\b/i, /\bux\b/i, /\btoken\b/i, /\btypography\b/i],
  },
  {
    topic: 'meeting',
    patterns: [/\bmeeting\b/i, /\bsync\b/i, /\bstandup\b/i, /\bcall\b/i],
  },
  {
    topic: 'review',
    patterns: [/\breview\b/i, /\bfeedback\b/i, /\bcheck\b/i, /\blook\b/i],
  },
];

export const questionResponses: Record<string, string[]> = {
  general: [
    'Good question. I can take a look and follow up.',
    'I can help with that. Let me check a couple of details.',
    'Not sure yet, but I will dig in and report back.',
    'I can check and circle back.',
    'Let me check and get back to you.',
    'I can look into it and follow up.',
    'I will check and update you.',
    'Give me a bit and I will check.',
    'I will check and let you know.',
    'Let me see what I can find.',
    'I can take a look and let you know.',
    'Let me double check.',
    'I will dig in and report back.',
    'Let me verify and follow up.',
    'I will poke around and report back.',
    'Let me dig into it and share an update.',
    'I will grab some details and circle back.',
    'Let me sanity check that real quick.',
    'I can take point and follow up.',
    'Let me pull the context and get back to you.',
    'I will check on it and drop an update.',
    'Give me a bit to confirm and I will reply.',
    'I will look into it now.',
    'Let me verify a couple things and respond.',
    'I can investigate and report back.',
    'Let me confirm the details.',
    'I will check with the team and update.',
    'Let me research that quickly.',
    'I can check the docs and reply.',
    'I will take a quick look and let you know.',
    'Let me see if I can reproduce and respond.',
    'I will validate and get back to you.',
    'I can check and keep you posted.',
    'Let me see where that stands.',
    'Let me check quickly and update you.',
    'I will verify and follow up soon.',
    'I can look into it and reply shortly.',
    'Let me check the details and respond.',
    'I will take a quick look and report back.',
    'Give me a sec, I will check.',
    'Let me peep that and reply.',
    'I will take a look and get back to you.',
    'Let me confirm and I will reply.',
    'I can check that and follow up.',
    'Let me look into it real quick.',
    'I will dig in and keep you posted.',
    'Let me check and I will update you.',
    'Give me a sec, I will check 👀',
    'Let me look into it real quick 👍',
    'I will check and update you soon 🔎',
    'I can look into it and reply ✅',
  ],
  planning: [
    'We should lock scope and owners. Want me to draft a quick checklist?',
    'I can summarize the milestones and send a quick recap.',
    'I can throw together a quick plan and share it.',
    'I can pull a quick plan and share.',
    'I can draft the outline and send it over.',
    'Want me to outline next steps?',
    'I can sketch a quick timeline.',
    'I can put together a draft plan.',
    'I can help break it down.',
    'I can make a quick milestone list.',
    'I can put the plan into a checklist.',
    'I can draft a rough timeline and owners.',
    'Let me pull together a quick scope summary.',
    'I can map the tasks and share a plan.',
    'I will outline the phases and post them.',
    'I can draft the next steps and post.',
    'I can propose a plan and we can adjust.',
    'I can draft the milestones and post them.',
    'I can outline the timeline and owners.',
    'Let me put together a quick plan.',
  ],
  release: [
    'I can check the pipeline and confirm the release timeline.',
    'I will verify the deploy status and post an update.',
    'I can take a look at the deploy and report back.',
    'I can check the deploy status and update you.',
    'I will keep an eye on it and report back.',
    'I can check the logs and update you.',
    'I will monitor and report back.',
    'Let me look at the pipeline and see.',
    'I can verify the rollout status.',
    'I can peek at the pipeline and report status.',
    'I will watch the rollout and send an update.',
    'I can check the deploy logs and reply.',
    'Let me confirm the release window.',
    'I will check the release checklist and update.',
    'I can validate the deploy and report back.',
    'I can review the pipeline history and share.',
    'I will check the rollout and update you.',
    'Let me verify the deployment status.',
    'I can check the release status and reply.',
  ],
  design: [
    'Happy to review the design options and share notes.',
    'We can do a quick review and decide on the direction.',
    'I can take a quick look and send notes.',
    'I can review and share some feedback.',
    'I can take a look and drop comments.',
    'I can review and share quick notes.',
    'Let me take a pass and share feedback.',
    'I can look at the design and respond.',
    'I can review and flag anything odd.',
    'I can review the layout and send feedback.',
    'I will take a pass and highlight any issues.',
    'I can review the components and share notes.',
    'Let me check the spacing and typography.',
    'I can review the mockups and reply.',
    'I will look it over and post comments.',
    'I can review the flow and share feedback.',
    'Let me check the UI details and reply.',
    'I can review and respond with notes.',
  ],
  meeting: [
    'I can join and capture notes if that helps.',
    'If you share a time, I can be there and take action items.',
    'I can hop on and take notes.',
    'I can join and help out.',
    'I can be there and take notes.',
    'I can join and keep track of action items.',
    'I will be there and take notes.',
    'I can jump in if needed.',
    'I can join and help facilitate.',
    'I will be there and capture action items.',
    'I can join and send a recap after.',
    'I will hop in and keep notes.',
    'I can join and send a recap.',
    'I will join and capture decisions.',
    'I can join and help with action items.',
  ],
  review: [
    'Yeah, I can review it and send feedback.',
    'Share the link and I will take a pass.',
    'I can review and drop comments.',
    'Send it over and I will review.',
    'I can take a look and share feedback.',
    'I can take a pass and share notes.',
    'I can review and send quick feedback.',
    'Share it and I will check it out.',
    'I can review it and send notes.',
    'I will review and comment soon.',
    'I can take a look and reply with feedback.',
    'I can do a quick review and send notes.',
    'I can review and drop notes shortly.',
    'I will review and share comments.',
    'I can take a pass and reply with notes.',
  ],
};

export const statementResponses: Record<string, string[]> = {
  general: [
    'Sounds good.',
    'Got it, thanks.',
    'Makes sense.',
    'Cool, thanks for the update.',
    'Cool.',
    'Nice.',
    'Gotcha.',
    'Sounds good to me.',
    'All good.',
    'Sweet, thanks.',
    'Ok cool.',
    'Alrighty.',
    'Yep, got it.',
    'All set.',
    'That works.',
    'Cool with me.',
    'Works for me.',
    'Sounds chill.',
    'All good on my end.',
    'Yep, sounds good.',
    'Nice, thanks.',
    'Ok, got it.',
    'Sweet.',
    'Cool, I am in.',
    'All set here.',
    'Got it, appreciate the heads-up.',
    'Thanks for sharing.',
    'Got it, makes sense.',
    'Sounds like a plan.',
    'Ok, I am aligned.',
    'Yep, I am good with that.',
    'All clear here.',
    'Works on my end.',
    'That tracks.',
    'Understood.',
    'Roger that.',
    'Yep, that works.',
    'Copy that.',
    'Looks good to me.',
    'Ok, I am in.',
    'Sounds right.',
    'Appreciate the update.',
    'Nice, good to know.',
    'Ok, I can roll with that.',
    'Sounds good, thanks.',
    'All good, appreciate it.',
    'Got it, thanks for the update.',
    'Ok, that makes sense.',
    'Yep, I am good with that.',
    'Sounds good on my side.',
    'Sounds good, I am in.',
    'Yep, all good here.',
    'Ok cool, thanks.',
    'Got it, thanks!',
    'All good, thanks.',
    'Ok, that works.',
    'That works for me too.',
    'Yep, sounds right.',
    'All good on my end.',
    'Cool, makes sense.',
    'All good 👍',
    'Sounds good 🙌',
    'Got it, thanks! ✅',
    'Ok, that works 😊',
    'Cool, I am in 🙌',
  ],
  planning: [
    'I can help pull together the plan and owners.',
    'Let us align on scope and any blockers.',
    'I can help get the plan in shape.',
    'I can help tidy up the plan.',
    'I can help with the plan if you want.',
    'I can help break it down.',
    'I can help get this organized.',
    'I can help draft the next steps.',
    'I can help sequence the tasks.',
    'Let us confirm scope and timing.',
    'I can help map out the phases.',
    'I can help draft owners and deadlines.',
    'I can help outline a timeline.',
    'I can help draft the milestones.',
    'I can help align scope and owners.',
  ],
  release: [
    'I will keep an eye on the pipeline and share updates.',
    'We should add a quick check in the deploy runbook.',
    'I can keep tabs on the deploy.',
    'I will keep an eye on the deploy.',
    'I can watch the pipeline and share updates.',
    'I can keep an eye on the rollout.',
    'I will watch it and let you know.',
    'I can check in on the deploy.',
    'I will monitor the rollout and share updates.',
    'I can watch the release and report back.',
    'I will keep an eye on it.',
    'I can keep tabs on the pipeline.',
    'I will monitor and send updates.',
    'I can keep an eye on the release.',
    'I can track the rollout and report back.',
  ],
  design: [
    'I like that direction. Let us capture the rationale.',
    'We can do a quick pass on spacing and hierarchy.',
    'That looks good to me.',
    'I like it.',
    'Looks solid.',
    'Looks good to me.',
    'Nice, I like that.',
    'That works.',
    'Nice, that direction feels right.',
    'That looks clean.',
    'I like the hierarchy there.',
    'That direction is solid.',
    'Looks great to me.',
    'Nice, that is clean.',
    'That looks polished.',
  ],
  meeting: [
    'Thanks for the heads-up. I will be there.',
    'I will add it to my calendar.',
    'I can make it.',
    'I will be there.',
    'Count me in.',
    'I am in.',
    'I can join.',
    'I will be there for sure.',
    'I will join and take notes.',
    'Yep, I can make it.',
    'I will be there, thanks.',
    'I can join, thanks for the invite.',
    'I will join and listen in.',
    'Count me in, thanks.',
    'I will be there, see you then.',
  ],
  review: [
    'I can take a look and leave comments.',
    'I will review and share notes shortly.',
    'I can review and send notes.',
    'I can review it later today.',
    'I will take a pass and reply.',
    'I can review and update you.',
    'I will take a look and reply.',
    'I can take a pass and share notes.',
    'I can review and drop comments.',
    'I will take a look and share feedback.',
    'I can review and send feedback.',
    'I can take a pass and send notes.',
    'I will review and share comments.',
    'I can take a look and reply soon.',
    'I will review and respond with notes.',
  ],
};

export const responseRules: ResponseRule[] = [
  {
    pattern: /[\p{Extended_Pictographic}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/u,
    responses: [
      'Love the emoji energy 😊',
      'Haha nice 😂',
      'Big mood 😅',
      'That is a vibe ✨',
      'Love that 🔥',
      'Nice one 👏',
      'Same 😂',
      'Lets goooo 🙌',
      'Mood 😎',
    ],
  },
  {
    pattern: /^(hi|hello|hey|yo|sup|good morning|good afternoon|good evening)\b/i,
    responses: [
      'Hey {name}!',
      'Hey there, {name}!',
      'Yo {name}!',
      'Hello {name}!',
      'Hey! What is up?',
      'Sup {name}?',
      'Heyyy {name}!',
      'What up {name}?',
      'Hey! Long time.',
      'Yo yo {name}!',
      'Hey! Good to see you.',
      'Hi {name}!',
      'Hello there!',
      'Heyyy!',
      'Yo!',
      'Hey hey!',
      'Hi there!',
      'Hey! How have you been?',
      'Hey {name}, welcome back!',
      'Yo {name}, what is new?',
      'Hey hey {name}!',
      'Hiya {name}!',
      'Hey there!',
      'Yo, good to see you.',
      'Hey {name}! How is it going?',
      'Hey {name}, good to see you.',
      'Yo {name}, welcome in.',
      'Hi {name}, good to see you.',
    ],
    maxLength: 24,
    usesName: true,
  },
  {
    pattern: /\b(agree|makes sense|that tracks|for sure|sounds right|exactly)\b/i,
    responses: [
      'Yep, agree.',
      'That tracks.',
      'Exactly.',
      'For sure.',
      'Yep, that makes sense.',
      'Agreed.',
      'Totally agree.',
      'Yep, sounds right.',
    ],
  },
  {
    pattern: /\b(what do you think|thoughts\?|any thoughts|opinions\?|how do you feel)\b/i,
    responses: [
      'I lean yes, but open to tweaks.',
      'My take: keep it simple for now.',
      'I would go with the simpler option.',
      'I like option A, but either works.',
      'I am good with either, slight lean to A.',
      'I think this is fine as-is.',
      'I would keep it as-is for now.',
      'My vote is to keep it minimal.',
    ],
  },
  {
    pattern: /\b(brb|be right back|back soon)\b/i,
    responses: [
      'Ok, no rush.',
      'We will be here.',
      'Take your time.',
      'All good, see you soon.',
      'Cool, catch you in a bit.',
    ],
  },
  {
    pattern: /\b(anyone here|anybody here|hello\?|ping\?|check in|checking in)\b/i,
    responses: [
      'Yep, I am here.',
      'Here!',
      'I am around.',
      'Still here.',
      'I am here, what is up?',
      'Yep, listening.',
    ],
  },
  {
    pattern: /\b(long time no see|miss you|missed you)\b/i,
    responses: [
      'Haha yeah, been a minute.',
      'Right? It has been a bit.',
      'Missed you too.',
      'Yeah, long time!',
      'Same, glad you are back.',
    ],
  },
  {
    pattern: /\b(you there|are you there)\b/i,
    responses: [
      'Yeah, I am here.',
      'Yep, what is up?',
      'Here, whats up?',
      'I am here.',
      'Yep, listening.',
    ],
  },
  {
    pattern: /\b(so\s+early|too\s+early|i\s+hate\s+mornings|monday)\b/i,
    responses: [
      'Monday energy is real.',
      'Too early, agreed.',
      'I feel that. Mornings are rough.',
      'Same, not a morning person.',
      'Yeah, mornings are not it.',
    ],
  },
  {
    pattern: /\b(already\?|seriously\?|bruh\?|come on)\b/i,
    responses: [
      'Lol, I know right.',
      'Seriously.',
      'Bruh, same.',
      'For real though.',
      'Yeah, that is wild.',
    ],
  },
  {
    pattern: /\b(guess what|you\'ll never guess|no way)\b/i,
    responses: [
      'No way, what happened?',
      'Ok, tell me.',
      'Now I am curious.',
      'You have my attention.',
      'Spill it.',
    ],
  },
  {
    pattern: /\b(fine\.|sure\.|whatever\.|ok\.)\b/i,
    responses: [
      'Lol ok then.',
      'Sure, ok.',
      'Alright, alright.',
      'Fair enough.',
      'You good? lol',
    ],
  },
  {
    pattern: /\b(sarcasm|sarcastic|jk)\b/i,
    responses: [
      'Haha yeah, I caught that.',
      'Lol, nice one.',
      'Ok, you got me.',
      'That sarcasm hit.',
      'Lol, fair.',
    ],
  },
  {
    pattern: /\b(you\'re the worst|you are the worst|rude)\b/i,
    responses: [
      'Lol rude.',
      'I know, I know.',
      'Wow ok 😂',
      'Haha, you love me though.',
      'That hurts 😅',
      'Ok, bully 😭',
      'Wow, who hurt you? 😂',
      'Oof, harsh but fair.',
    ],
  },
  {
    pattern: /\b(roast me|roast|drag me)\b/i,
    responses: [
      'You asked for it 😂',
      'Easy there, I am not trying to end you.',
      'Ok ok, I will be nice... maybe.',
      'I could roast you but I am trying to be a good friend 😇',
      'Nah, I will keep it friendly.',
      'You sure about that? 😂',
    ],
  },
  {
    pattern: /\b(ouch|rude|mean)\b/i,
    responses: [
      'Lol sorry, love you though.',
      'Ok ok, I will chill.',
      'Fair, that was a little much 😅',
      'I am kidding, you are great.',
      'Alright, my bad 😅',
    ],
  },
  {
    pattern: /\b(lol|haha)\b.*\b(rude|mean|toxic)\b/i,
    responses: [
      'Haha, I am just playing.',
      'Ok ok, I will behave 😇',
      'Lol, I am kidding.',
      'I am joking, promise.',
      'Alright, I will chill 😅',
    ],
  },
  {
    pattern: /\b(you\'re so|you are so)\b.*\b(annoying|dramatic|extra|lazy)\b/i,
    responses: [
      'Ok, and? 😂',
      'Guilty as charged.',
      'Wow, called out.',
      'Rude, but fair 😅',
      'You are not wrong.',
    ],
  },
  {
    pattern: /\b(cringe|cringy)\b/i,
    responses: [
      'Let me live 😂',
      'Cringe but make it cute.',
      'Ok ok, I hear you.',
      'Fair, that was a little cringe.',
      'Leave me alone 😭',
    ],
  },
  {
    pattern: /\b(skill issue|git gud)\b/i,
    responses: [
      'Ok gamer 😂',
      'Reported for toxicity 😅',
      'Alright, calm down pro.',
      'Wow, rude.',
      'You got jokes today 😂',
    ],
  },
  {
    pattern: /\b(whatever|meh)\b/i,
    responses: [
      'Lol ok.',
      'Alright then.',
      'Fair enough.',
      'Cool, cool.',
      'You good? 😂',
    ],
  },
  {
    pattern: /\b(wyd|what are you up to|what\'s up)\b/i,
    responses: [
      'Not much, you?',
      'Just chilling, you?',
      'Same, just hanging.',
      'Not a ton, what about you?',
      'Just here, what is up?',
    ],
  },
  {
    pattern: /\b(haha|lol)\b.*\b(you\'re|you are)\b/i,
    responses: [
      'Lol, you know it.',
      'Haha, yeah that is me.',
      'Ok ok, fair.',
      'Lol, guilty.',
      'You are not wrong 😂',
    ],
  },
  {
    pattern: /\b(does that work|works for you|ok with you|sound good\?|cool\?)\b/i,
    responses: [
      'Yep, works for me.',
      'Sounds good.',
      'Yep, I am good with that.',
      'Works on my end.',
      'All good here.',
      'Cool with me.',
      'Yep, that works.',
    ],
  },
  {
    pattern: /\b(can you|could you|would you|can someone|anyone)\b.*\b(help|take|check|review|look|pick up)\b/i,
    responses: [
      'Yep, I can take that.',
      'I can handle it.',
      'I can grab that.',
      'I can take a look.',
      'I can pick that up.',
      'I will handle it.',
      'I can do that.',
    ],
  },
  {
    pattern: /\b(when|eta|by when|timeline|deadline)\b/i,
    responses: [
      'I can share an ETA shortly.',
      'Let me confirm timing and reply.',
      'I will check the timeline and update.',
      'I can post an ETA soon.',
      'Let me confirm the deadline and update.',
    ],
  },
  {
    pattern: /\b(todo|to-do|task list|checklist)\b/i,
    responses: [
      'I can put together a quick checklist.',
      'Want me to draft a task list?',
      'I can outline a quick to-do list.',
      'I can share a checklist.',
      'I will draft a quick list.',
    ],
  },
  {
    pattern: /\b(share|send)\b.*\b(link|doc|file|spec|notes)\b/i,
    responses: [
      'Yep, please share the link.',
      'Send it over and I will look.',
      'Drop the doc and I will review.',
      'Share the file and I will check.',
      'Send the notes and I will read.',
    ],
  },
  {
    pattern: /\b(what\'s next|next steps|follow up|follow-up)\b/i,
    responses: [
      'I can outline the next steps.',
      'I will post a quick next-steps list.',
      'I can draft the follow-ups.',
      'I will summarize next steps.',
      'I can share a quick recap of next steps.',
    ],
  },
  {
    pattern: /\b(approve|approved|looks good to me|lgtm)\b/i,
    responses: [
      'LGTM.',
      'Looks good to me.',
      'Approved on my end.',
      'All good from me.',
      'Ship it.',
    ],
  },
  {
    pattern: /\b(blocked|stuck|blocked on|stuck on)\b/i,
    responses: [
      'What are you blocked on?',
      'I can help unblock that.',
      'Want me to take a look?',
      'Share details and I will help.',
      'Let me know what you need.',
    ],
  },
  {
    pattern: /\b(what happened|root cause|why did)\b/i,
    responses: [
      'Let me dig into the root cause.',
      'I can investigate and report back.',
      'I will check the logs and update.',
      'Let me see what happened and reply.',
      'I will dig in and share details.',
    ],
  },
  {
    pattern: /\b(awesome|amazing|love it|so good)\b/i,
    responses: [
      'Love that.',
      'So good.',
      'That is awesome.',
      'Nice, love it.',
      'Yeah, that is great.',
    ],
  },
  {
    pattern: /\b(thanks|thank you|appreciate it|thx)\b/i,
    responses: [
      'No problem!',
      'Anytime!',
      'You got it.',
      'Glad to help.',
      'For sure.',
      'Yep, no worries.',
      'Totally.',
      'All good!',
      'Happy to help!',
      'No worries at all.',
      'All good, anytime.',
      'No sweat.',
      'Any time at all.',
      'Of course.',
      'For sure, happy to help.',
      'No worries, anytime.',
      'You got it, happy to help.',
      'All good, glad to help.',
      'Anytime, no problem.',
    ],
  },
  {
    pattern: /\b(how are you|how's it going|how is it going|hru|what's up|whats up)\b/i,
    responses: [
      'Doing good! You?',
      'Pretty chill, you?',
      'All good here. You?',
      'Doing fine, thanks! You?',
      'Not bad! What about you?',
      'Chilling, you?',
      'Doing alright. You?',
      'All good. What about you?',
      'Doing great, thanks. You?',
      'Solid. How about you?',
      'Doing ok. You?',
      'Not too bad, you?',
      'Hanging in there. You?',
      'Just vibing. You?',
      'All good on my end. You?',
      'Doing good, how about you?',
      'Pretty good, you?',
      'Doing fine, how about you?',
      'All good here, you?',
      'Doing fine over here, you?',
      'Pretty good here, you?',
    ],
  },
  {
    pattern: /\b(lol|lmao|haha|ha ha|rofl)\b/i,
    responses: [
      'Haha yeah.',
      'Lol true.',
      'Haha, for real.',
      'Lol, same.',
      'Haha that is great.',
      'Lol nice.',
      'Haha, love that.',
      'Lol yup.',
      'Haha, fair.',
      'Lol, that is good.',
      'Haha, agreed.',
      'Lol, true that.',
      'Haha, I feel that.',
      'Lol, totally.',
      'Haha, true.',
      'Lol, same.',
      'Haha, no way.',
      'Lol, facts.',
      'Haha, that is wild.',
      'Lol 😂',
      'Haha 😂',
      'Lmao 🤣',
      'Haha, that got me 😂',
    ],
  },
  {
    pattern: /\b(bro|dude|fam|bestie|buddy|pal|homie|mate)\b/i,
    responses: [
      'Haha for sure, fam.',
      'I got you, dude.',
      'All good, homie.',
      'You got it, buddy.',
      'For sure, pal.',
      'Lol, facts.',
      'Yep, I feel you.',
      'No worries, fam.',
      'Say less, I got it.',
      'Bet, I am on it.',
      'For real though.',
      'You are good, dude.',
      'All good, bestie.',
      'We are good, mate.',
      'Chill, I got you.',
      'Haha, I got you.',
      'Lowkey, same.',
      'Highkey, same.',
      'Straight up, same.',
      'Big mood.',
      'For sure, fam 🤝',
      'I got you, dude 👍',
      'All good, homie 🙌',
      'Say less 😎',
      'Bet, I am in 🤝',
      'Big mood 😂',
    ],
  },
  {
    pattern: /\b(omg|lmk|frfr|no cap|deadass|lowkey|highkey|bet|facts|mood)\b/i,
    responses: [
      'Facts.',
      'No cap.',
      'Big mood.',
      'Lowkey, same.',
      'Highkey, same.',
      'Bet, say less.',
      'Frfr.',
      'Deadass, same.',
      'Lmk, I am down.',
      'For real, I feel that.',
      'Omg, same.',
      'Facts, for real.',
      'Bet, I got you.',
      'Say less, I am in.',
      'That is a vibe.',
      'I am down, lmk.',
      'Facts, love that.',
      'No cap 🧢',
      'Big mood 😅',
      'Lowkey, same 😅',
      'Highkey, same 😅',
      'Bet, say less 😎',
      'Frfr 🤝',
      'Omg same 😂',
    ],
  },
  {
    pattern: /\b(nice|awesome|sick|dope|fire|clean|well done)\b/i,
    responses: [
      'That is fire 🔥',
      'So good 🔥',
      'That is clean ✨',
      'Nice one 👏',
      'That is dope 😎',
      'Looks great 🙌',
      'That is solid 👍',
    ],
  },
  {
    pattern: /\b(sorry|my bad|my fault|oops)\b/i,
    responses: [
      'No worries!',
      'All good.',
      'You are good.',
      'No stress.',
      'Totally fine.',
      'It happens.',
      'No big deal.',
      'All good, really.',
      'You are all good.',
      'All good, no worries.',
      'No worries at all.',
      'All good, thanks for saying that.',
      'Totally fine, no stress.',
    ],
  },
  {
    pattern: /\b(brb|be right back|back in a sec)\b/i,
    responses: [
      'All good, see you in a sec.',
      'Ok, I will be here.',
      'No rush.',
      'Sounds good, take your time.',
      'All good, take your time.',
      'Sure, no rush.',
    ],
  },
  {
    pattern: /\b(running late|late|delayed)\b/i,
    responses: [
      'No worries, thanks for the heads-up.',
      'All good, see you when you get here.',
      'Sounds good, take your time.',
      'Ok, thanks for the update.',
      'All good, thanks for letting us know.',
      'No problem, see you soon.',
    ],
  },
  {
    pattern: /\b(busy|swamped|heads down|in a meeting)\b/i,
    responses: [
      'All good, ping me when you are free.',
      'No worries, we can sync later.',
      'Got it, catch you later.',
      'Ok, talk later.',
      'No worries, we can connect later.',
      'Got it, ping me when free.',
    ],
  },
  {
    pattern: /\b(congrats|congratulations|nice job|well done|great job)\b/i,
    responses: [
      'Nice! Congrats!',
      'Let\'s go! Congrats.',
      'Huge win, nice job.',
      'Well deserved!',
      'Big win, congrats!',
      'Congrats, that is awesome.',
      'Congrats, great job!',
      'Well done, congrats!',
    ],
  },
  {
    pattern: /\b(good luck|you got this|fingers crossed)\b/i,
    responses: [
      'You got this!',
      'Good luck!',
      'Rooting for you.',
      'You will crush it.',
      'You got it, go for it.',
      'Good luck, you got this.',
    ],
  },
  {
    pattern: /\b(gg|good game|well played)\b/i,
    responses: [
      'GG!',
      'Well played!',
      'Nice game.',
      'GGs.',
      'GG, well played.',
      'Nice, well played.',
    ],
  },
  {
    pattern: /\b(excited|hyped|cant wait|can't wait|stoked)\b/i,
    responses: [
      'Same, I am hyped.',
      'Yeah, I am excited too.',
      'Let\'s go!',
      'This is going to be fun.',
      'Same, this is exciting.',
      'I am hyped too.',
      'I am excited too.',
      'This is going to be great.',
    ],
  },
  {
    pattern: /\b(tired|sleepy|exhausted|beat)\b/i,
    responses: [
      'Same, I am wiped.',
      'Feel that. Get some rest.',
      'Yeah, it has been a long day.',
      'Go recharge, you deserve it.',
      'Same, I am tired too.',
      'Rest up when you can.',
    ],
  },
  {
    pattern: /\b(food|lunch|dinner|breakfast|snack|coffee)\b/i,
    responses: [
      'Now you have me hungry too.',
      'Nice, what are you getting?',
      'Sounds good. Enjoy!',
      'Good call, I might grab something too.',
      'Food sounds amazing right now.',
      'Nice, treat yourself.',
      'Yum, now I want food too.',
      'Solid choice.',
      'That sounds great.',
      'Enjoy, that sounds good.',
      'That sounds so good.',
      'Enjoy it!',
    ],
  },
  {
    pattern: /\b(welcome|welcome aboard|glad you're here)\b/i,
    responses: [
      'Welcome in!',
      'Glad you are here.',
      'Welcome! Happy to have you.',
      'Hey, welcome!',
      'Welcome! Nice to have you here.',
      'Hey, glad you are here.',
    ],
  },
  {
    pattern: /\b(bye|goodbye|see ya|see you|later|gn|good night|night)\b/i,
    responses: [
      'Later!',
      'See you!',
      'Bye!',
      'Good night!',
      'Catch you later!',
      'See you soon!',
      'Night!',
    ],
  },
  {
    pattern: /\b(lets go|let's go|lfggg|ggs|w)\b/i,
    responses: [
      'Lets gooo!',
      'W.',
      'So hyped!',
      'GGs!',
      'That is a win.',
      'Big W.',
      'Lets go!',
      'So good.',
      'Huge W.',
      'Lets go, love it.',
    ],
  },
  {
    pattern: /\b(jk|just kidding|kidding)\b/i,
    responses: [
      'Lol ok.',
      'Haha got me.',
      'Alright alright.',
      'Ok, fair.',
      'Haha nice one.',
      'Lol, I see you.',
      'Haha, good one.',
      'Lol, fair enough.',
    ],
  },
  {
    pattern: /\b(bet|fr|ngl|idk|tbh|imo|imho|smh|bruh|sus|wtf|wth|lmk|lowkey|highkey|cap|no cap|deadass|frfr|rn|afaik|ik|iykyk|fyi|tbh|g2g|omw|ggs)\b/i,
    responses: [
      'Bet.',
      'Fr.',
      'Ngl, same.',
      'Idk tbh.',
      'Tbh yeah.',
      'Imo that works.',
      'Smh lol.',
      'Bruh, same.',
      'Sus, but ok.',
      'W.',
      'Lmk.',
      'Fr fr.',
      'Ngl, that is fair.',
      'Idk yet, tbh.',
      'Lowkey yeah.',
      'Highkey same.',
      'Bruh, for real.',
      'Fr, same.',
      'Ngl, true.',
      'Bet, I got you.',
      'Lmk when.',
      'No cap.',
      'Deadass.',
      'Frfr.',
      'Lowkey true.',
      'Highkey true.',
      'Cap.',
      'IYKYK.',
      'Fyi.',
      'Afaik, yeah.',
      'Omw.',
      'G2g, brb.',
      'Fr, agreed.',
      'Ngl, that is real.',
      'Lowkey facts.',
      'Highkey facts.',
      'Bet, sounds good.',
      'Lmk if anything changes.',
      'No cap, true.',
      'Fr, I feel that.',
    ],
  },
  {
    pattern: /\b(bored|boring|nothing to do)\b/i,
    responses: [
      'Same, it is slow today.',
      'I feel that. Anything fun to do?',
      'We should start a game or something.',
      'Bored too. Want to chat?',
      'Same, slow day.',
      'We should do something fun.',
      'Same, it is quiet today.',
      'Anything interesting going on?',
    ],
  },
  {
    pattern: /\b(hungry|starving)\b/i,
    responses: [
      'Same. Food sounds so good.',
      'Now I want a snack too.',
      'What are you craving?',
      'Go grab something, you deserve it.',
      'Same, I need food.',
      'Go grab a snack.',
      'Same, I am hungry too.',
      'Food sounds good right now.',
    ],
  },
  {
    pattern: /\b(confused|lost|not following|dont get it|don't get it)\b/i,
    responses: [
      'Same, I am a little lost.',
      'I can try to help. What part?',
      'Let me reread that.',
      'Yeah, that is confusing.',
      'Same here, let me look again.',
      'Yeah, that is not clear.',
    ],
  },
  {
    pattern: /\b(nice|awesome|sick|dope|fire|clean|well done)\b/i,
    responses: [
      'Yeah, that is solid.',
      'So good.',
      'That is clean.',
      'Nice one.',
      'That is fire.',
      'That is dope.',
      'That looks great.',
    ],
  },
  {
    pattern: /\b(you got this|you can do it|you got it)\b/i,
    responses: [
      'You got this.',
      'You are good, keep going.',
      'You will be fine.',
      'I believe in you.',
      'You got it.',
      'You can do this.',
    ],
  },
  {
    pattern: /\b(stressed|stressing|overwhelmed|burned out|burnt out)\b/i,
    responses: [
      'That sounds rough. Take a breather.',
      'You got this. One thing at a time.',
      'Totally feel that. Hang in there.',
      'Take a break if you can.',
      'That is a lot. Take a breather.',
      'Hang in there, you got this.',
    ],
  },
  {
    pattern: /\b(weekend|friday|saturday|sunday)\b/i,
    responses: [
      'Weekend plans?',
      'Hope you get some rest this weekend.',
      'Finally, weekend is close.',
      'Weekend vibes.',
      'Hope the weekend is chill.',
      'Weekend is almost here.',
    ],
  },
  {
    pattern: /\b(shrug|idk|who knows|whatever)\b/i,
    responses: [
      'Idk, maybe.',
      'Who knows.',
      'Hard to say.',
      'Could go either way.',
      'Not sure honestly.',
      'Not sure, maybe.',
      'Could be, hard to say.',
    ],
  },
  {
    pattern: /\b(checking|looking|on it|i got it|got it)\b/i,
    responses: [
      'Nice, thanks.',
      'Sounds good.',
      'Ok cool.',
      'Appreciate it.',
      'Thanks for handling it.',
      'Nice, thanks for taking it.',
      'Sounds good, thanks.',
    ],
  },
  {
    pattern: /\b(wait|hold on|sec|one sec|one second)\b/i,
    responses: [
      'All good.',
      'No rush.',
      'Take your time.',
      'Yep, one sec.',
      'Ok, waiting.',
      'Sure, take your time.',
      'No rush at all.',
    ],
  },
  {
    pattern: /^(ok|okay|k|kk|sure|yeah|yep|yup|alright|fine|sounds good)\b/i,
    responses: [
      'Yep, sounds good.',
      'Ok cool.',
      'Got it.',
      'Sure thing.',
      'Yeah, works for me.',
      'Alright, sounds good.',
      'Yep, works.',
      'All good with me.',
      'Sounds good here.',
      'Yep, I am in.',
      'Ok, sounds good.',
      'That works for me.',
      'Yep, all good.',
      'Sure, sounds good.',
      'Ok, works for me.',
      'Yep, I am good.',
      'Yep, works for me.',
      'Ok, sounds good to me.',
    ],
    maxLength: 16,
  },
  {
    pattern: /^\?$|^(what\?|who\?|where\?|when\?|why\?)$/i,
    responses: [
      'Not sure yet.',
      'Let me check.',
      'I will find out.',
      'Give me a sec.',
      'One sec, checking.',
      'Let me see.',
      'I will check that.',
    ],
  },
  {
    pattern: /\b(maybe|not sure|idk|i dunno|unsure)\b/i,
    responses: [
      'Maybe. I will see.',
      'Not sure yet.',
      'Possibly.',
      'I will let you know.',
      'Could be, I will check.',
      'Not sure, but maybe.',
      'Could be, I will see.',
      'Maybe, I will check.',
      'Possibly, I will see.',
      'Maybe, I will check into it.',
      'Not sure yet, I will check.',
    ],
  },
  {
    pattern: /^(yes|no|nah|nope|yep|yeah)\b/i,
    responses: [
      'Yep.',
      'Nope.',
      'Yeah.',
      'Nah.',
      'For sure.',
      'Not really.',
      'Sure.',
      'Nope, not yet.',
      'Yeah, for sure.',
      'Nah, not yet.',
    ],
  },
];
